apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: maheshvenkata133/telugu-evolution:latest  # <-- Jenkins replaces this, if this image not avaiabe then use this --> nginx:latest
        ports:
        - containerPort: 80
